"""
Script Agent — writes a Raven & Jax dialogue script for the selected event.
Output: runs/YYYY-MM-DD/script.md
"""

import json
import anthropic
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import ANTHROPIC_API_KEY, CLAUDE_MODEL, SCRIPT_MAX_WORDS, SCRIPT_MIN_WORDS


SYSTEM_PROMPT = """You write short comedy scripts for a YouTube/TikTok series called "Raven & Jax."

The format is a modern couple on their couch reacting to a real global news event.
The script is 150-200 words of natural dialogue — enough for 1-2 minutes when spoken.

CHARACTER BIBLES:

RAVEN (wife):
- Conspiracy-smart, sharp, dry humor
- Connects dots, sees patterns, usually right
- Talks fast when excited about a theory
- Catchphrases: "I literally told you this would happen." / "There are no coincidences." / "Jax. JAX. Look at me."

JAX (husband):
- Lovably drunk, clueless, warm
- Processes everything 30 seconds late
- Accidentally says profound things
- Catchphrases: "Wait — who's that again?" / "Okay but is that bad?" / "That's wild. You want another beer?"

RULES:
- Start in the middle of the conversation — they're already watching the news
- No exposition — feel like you're eavesdropping on a real couple
- Raven drives the topic, Jax reacts
- End on a punchline or Jax's accidental wisdom
- Format: RAVEN: [line] / JAX: [line] / etc.
- Max 200 words total dialogue
- Never reference real politicians by full name in a way that could be defamatory"""


def _fallback_script(event: dict) -> str:
    h = event["headline"]
    return f"""RAVEN: Okay, did you see this? {h}
JAX: Wait — what? When did that happen?
RAVEN: Like, today, Jax. I literally told you this would happen.
JAX: You did not tell me that.
RAVEN: I one hundred percent told you that. There are no coincidences.
JAX: Okay but is that bad?
RAVEN: Is that bad. JAX. Look at me. Yes. It is bad.
JAX: Huh. That's wild. You want another beer?
RAVEN: I want answers. But also yes."""


def write_script(event: dict) -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    user_prompt = (
        f"Today's news event: {event['headline']}\n"
        f"Summary: {event['summary']}\n"
        f"Comedy angle: {event.get('comedy_angle', '')}\n\n"
        "Write the Raven & Jax script reacting to this event. "
        "Make it funny, natural, and punchy."
    )

    try:
        message = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=1024,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
        return message.content[0].text.strip()
    except Exception as e:
        print(f"[script_agent] Claude unavailable ({e.__class__.__name__}), using template script fallback.")
        return _fallback_script(event)


def count_words(script: str) -> int:
    lines = [l for l in script.split("\n") if l.strip()]
    dialogue = " ".join(
        l.split(":", 1)[1].strip() if ":" in l else l
        for l in lines
    )
    return len(dialogue.split())


def run(run_dir: Path) -> Path:
    event_file = run_dir / "selected-event.json"
    event_data = json.loads(event_file.read_text())
    event = event_data["selected"]

    print(f"[script_agent] Writing script for: \"{event['headline']}\"...")

    script = write_script(event)
    word_count = count_words(script)

    # Retry once if too short
    if word_count < SCRIPT_MIN_WORDS:
        print(f"[script_agent] Script too short ({word_count} words), retrying...")
        script = write_script(event)
        word_count = count_words(script)

    out_content = f"""# Raven & Jax — {run_dir.name}

**Event:** {event['headline']}
**Words:** ~{word_count}

---

{script}

---
*Generated by Comedy Factory*
"""

    out_file = run_dir / "script.md"
    out_file.write_text(out_content)
    print(f"[script_agent] Script written ({word_count} words) → {out_file}")
    return out_file


if __name__ == "__main__":
    from datetime import date
    run_dir = Path(__file__).parent.parent / "runs" / date.today().isoformat()
    run(run_dir)
